[package]
name = "afterburner-core"
version.workspace = true
edition.workspace = true

[dependencies]
tracing = { workspace = true }
tracing-test = { workspace = true }
thiserror = { workspace = true }
