[workspace]
resolver = "2"
members = ["crates/afterburner-core", "crates/afterburner-cpu"]

[workspace.package]
name = "afterburner"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tracing = "0.1"
tracing-test = "0.2"
thiserror = "2"
