[workspace]
resolver = "2"
members = ["shaders", "builder"]

[workspace.package]
name = "afterburner-shaders"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
spirv-std = "0.9"
spirv-builder = "0.9"
