[workspace]
resolver = "2"
members = ["afterburner-shaders", "builder"]

[workspace.package]
name = "afterburner-shaders"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
spirv-builder = "0.9"
tracing = "0.1"
tracing-test = "0.2"
