[package]
name = "afterburner-cpu"
version.workspace = true
edition.workspace = true

[dependencies]
afterburner-core = { path = "../afterburner-core" }
tracing = { workspace = true }
tracing-test = { workspace = true }
